export const actionTypes = {
  TODO_DONE: "TODO_DONE",
  TODO_DELETE: "TODO_DELETE",
  FILTER_CHANGE: "FILTER_CHANGE_TODO",
  FILTER_QUERY_SEARCH: "FILTER_QUERY_SEARCH",
  TODO_ADD: "TODO_ADD ",
  TODO_CHANGE: "TODO_CHANGE",
};
